/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PrometheusController_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo mới phòng ban (Tự động tính toán Closure Table) */
        post: operations["DepartmentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy sơ đồ tổ chức (Dạng Cây - Đã lọc các phòng ban bị xóa) */
        get: operations["DepartmentsController_getTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}/descendants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy toàn bộ phòng ban con/cháu/chắt... (tốc độ < 1ms) */
        get: operations["DepartmentsController_getDescendants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy thông tin 1 phòng ban */
        get: operations["DepartmentsController_findOne"];
        put?: never;
        post?: never;
        /** Xóa mềm phòng ban (Soft Delete) */
        delete: operations["DepartmentsController_remove"];
        options?: never;
        head?: never;
        /** Cập nhật phòng ban (Cấm sửa phòng ban cha) */
        patch: operations["DepartmentsController_update"];
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách vai trò (Có phân trang & Sắp xếp) */
        get: operations["RolesController_findAll"];
        put?: never;
        /** Tạo vai trò mới */
        post: operations["RolesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy thông tin 1 vai trò */
        get: operations["RolesController_findOne"];
        put?: never;
        post?: never;
        /** Xóa vai trò */
        delete: operations["RolesController_remove"];
        options?: never;
        head?: never;
        /** Cập nhật vai trò */
        patch: operations["RolesController_update"];
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách người dùng (Có phân trang & Sắp xếp) */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Tạo tài khoản người dùng */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy chi tiết 1 người dùng */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /** Xóa tài khoản */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /** Cập nhật thông tin */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập vào hệ thống */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng ký doanh nghiệp mới (Onboarding SaaS) */
        post: operations["AuthController_registerTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách các Entities (Có phân trang & Sắp xếp) */
        get: operations["EntitiesController_findAll"];
        put?: never;
        /** Tạo Entity mới (VD: Phiếu xin nghỉ) */
        post: operations["EntitiesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy chi tiết Entity kèm danh sách các trường (Fields) */
        get: operations["EntitiesController_findOne"];
        put?: never;
        post?: never;
        /** Xóa Entity */
        delete: operations["EntitiesController_remove"];
        options?: never;
        head?: never;
        /** Cập nhật thông tin Entity */
        patch: operations["EntitiesController_update"];
        trace?: never;
    };
    "/api/v1/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách các trường dữ liệu của 1 Entity */
        get: operations["FieldsController_findAllByEntity"];
        put?: never;
        /** Tạo trường dữ liệu mới vào Entity */
        post: operations["FieldsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy chi tiết 1 trường dữ liệu */
        get: operations["FieldsController_findOne"];
        put?: never;
        post?: never;
        /** Xóa trường dữ liệu */
        delete: operations["FieldsController_remove"];
        options?: never;
        head?: never;
        /** Cập nhật trường dữ liệu */
        patch: operations["FieldsController_update"];
        trace?: never;
    };
    "/api/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách bản ghi phân trang, tìm kiếm và lọc động vạn năng (Áp dụng RLS) */
        get: operations["RecordsController_findAllByEntity"];
        put?: never;
        /** Thêm mới một bản ghi (Submit Form) */
        post: operations["RecordsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/lookup/{fieldId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách dữ liệu tra cứu liên kết động chéo biểu mẫu */
        get: operations["RecordsController_getLookupData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy chi tiết 1 bản ghi */
        get: operations["RecordsController_findOne"];
        put?: never;
        post?: never;
        /** Xóa bản ghi */
        delete: operations["RecordsController_remove"];
        options?: never;
        head?: never;
        /** Cập nhật nội dung bản ghi (Tự động ghi Log Lịch sử) */
        patch: operations["RecordsController_update"];
        trace?: never;
    };
    "/api/v1/records/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy lịch sử các lần chỉnh sửa dữ liệu (Audit Trail) */
        get: operations["RecordsController_getRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách Quy trình (Đã lọc theo tầm nhìn phân quyền, có phân trang & sắp xếp) */
        get: operations["WorkflowsController_findAll"];
        put?: never;
        /** Tạo mới một Quy trình */
        post: operations["WorkflowsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy chi tiết Quy trình kèm các Phiên bản */
        get: operations["WorkflowsController_findOne"];
        put?: never;
        post?: never;
        /** Xóa Quy trình */
        delete: operations["WorkflowsController_remove"];
        options?: never;
        head?: never;
        /** Cập nhật tên/mô tả Quy trình */
        patch: operations["WorkflowsController_update"];
        trace?: never;
    };
    "/api/v1/workflows/{id}/versions/{versionId}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nhân bản một Version thành Version mới */
        post: operations["WorkflowsController_cloneVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{id}/versions/{versionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cập nhật trạng thái Version */
        patch: operations["WorkflowsController_updateVersionStatus"];
        trace?: never;
    };
    "/api/v1/workflows/instances/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Khởi chạy luồng quy trình cho 1 bản ghi (Trình ký phiếu) */
        post: operations["WorkflowsController_startInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/instances/{id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Thực hiện Phê duyệt hoặc Từ chối phiếu */
        post: operations["WorkflowsController_handleAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/instances/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy lịch sử Audit Log phê duyệt của lượt chạy */
        get: operations["WorkflowsController_getInstanceLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow-pipeline/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo bước duyệt mới vào Version DRAFT */
        post: operations["WorkflowStepsController_createStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow-pipeline/steps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Xóa bước duyệt */
        delete: operations["WorkflowStepsController_removeStep"];
        options?: never;
        head?: never;
        /** Cập nhật bước duyệt */
        patch: operations["WorkflowStepsController_updateStep"];
        trace?: never;
    };
    "/api/v1/workflow-pipeline/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo đường rẽ nhánh giữa 2 Bước */
        post: operations["WorkflowStepsController_createTransition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow-pipeline/transitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Xóa đường rẽ nhánh */
        delete: operations["WorkflowStepsController_removeTransition"];
        options?: never;
        head?: never;
        /** Cập nhật logic rẽ nhánh */
        patch: operations["WorkflowStepsController_updateTransition"];
        trace?: never;
    };
    "/api/v1/workflow-pipeline/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy toàn bộ sơ đồ các bước và rẽ nhánh */
        get: operations["WorkflowStepsController_getPipeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/print-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo mới một mẫu in cho Biểu mẫu */
        post: operations["PrintTemplatesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/print-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy chi tiết cấu hình mẫu in */
        get: operations["PrintTemplatesController_findOne"];
        put?: never;
        post?: never;
        /** Xóa mẫu in */
        delete: operations["PrintTemplatesController_remove"];
        options?: never;
        head?: never;
        /** Cập nhật mẫu in */
        patch: operations["PrintTemplatesController_update"];
        trace?: never;
    };
    "/api/v1/print-templates/{id}/render/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Biên dịch dữ liệu bản ghi vào Mẫu in ra mã HTML hoàn chỉnh */
        get: operations["PrintTemplatesController_renderTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/entities-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thống kê lượng bản ghi (phiếu) theo từng biểu mẫu */
        get: operations["AnalyticsController_getEntitiesSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/workflows-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thống kê trạng thái phê duyệt của các quy trình */
        get: operations["AnalyticsController_getWorkflowsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/spending-by-department": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Báo cáo vĩ mô: Thống kê tổng ngân sách đề xuất theo từng Phòng ban (Bóc tách JSONB) */
        get: operations["AnalyticsController_getSpendingByDepartment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tải tệp đính kèm lên Cloudflare R2 / S3 */
        post: operations["AttachmentsController_uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/{id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy đường dẫn có chữ ký số (Presigned URL) có hiệu lực 15 phút */
        get: operations["AttachmentsController_getPresignedUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Xóa tệp tin */
        delete: operations["AttachmentsController_removeFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách thông báo (Có phân trang) */
        get: operations["NotificationsController_findAllForUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kênh truyền tin thông báo thời gian thực (SSE) */
        get: operations["NotificationsController_streamNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Đánh dấu đã đọc một thông báo */
        patch: operations["NotificationsController_markAsRead"];
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Đánh dấu đã đọc TOÀN BỘ thông báo */
        patch: operations["NotificationsController_markAllAsRead"];
        trace?: never;
    };
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách nhật ký hành chính (Phân trang) */
        get: operations["AuditLogsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy toàn bộ danh sách doanh nghiệp (Có phân trang & Sắp xếp) */
        get: operations["TenantsController_findAll"];
        put?: never;
        /** Tạo một doanh nghiệp mới */
        post: operations["TenantsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy thông tin chi tiết doanh nghiệp kèm số lượng tài khoản/dữ liệu */
        get: operations["TenantsController_findOne"];
        put?: never;
        post?: never;
        /** Xóa vĩnh viễn doanh nghiệp & toàn bộ dữ liệu liên đới (Cascade Delete) */
        delete: operations["TenantsController_remove"];
        options?: never;
        head?: never;
        /** Cập nhật thông tin doanh nghiệp */
        patch: operations["TenantsController_update"];
        trace?: never;
    };
    "/api/v1/mailer/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gửi email test đến địa chỉ thật */
        post: operations["MailerController_testEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/my-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách nhiệm vụ của tôi (Có phân trang & lọc trạng thái) */
        get: operations["TasksController_findMyTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thống kê KPI xử lý nhiệm vụ toàn công ty (Dành cho Quản lý) */
        get: operations["TasksController_getAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hoàn thành nhiệm vụ (Tự động tính thời gian SLA) */
        post: operations["TasksController_completeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/delegate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ủy quyền nhiệm vụ cho người khác */
        post: operations["TasksController_delegateTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy toàn bộ danh sách Task (Super Admin) */
        get: operations["TasksController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateDepartmentDto: {
            /**
             * @description Tên phòng ban
             * @example Phòng Kỹ thuật
             */
            name: string;
            /**
             * @description ID của phòng ban cha (nếu có)
             * @example 1
             */
            parentId?: number;
        };
        UpdateDepartmentDto: {
            /**
             * @description Tên phòng ban
             * @example Phòng Kỹ thuật
             */
            name?: string;
        };
        CreateRoleDto: {
            /**
             * @description Tên vai trò
             * @example System Admin
             */
            name: string;
            /**
             * @description Cấu hình quyền dạng JSON
             * @example {
             *       "users": [
             *         "CREATE",
             *         "READ",
             *         "UPDATE",
             *         "DELETE"
             *       ],
             *       "workflows": [
             *         "READ"
             *       ]
             *     }
             */
            permissions?: Record<string, never>;
        };
        UpdateRoleDto: {
            /**
             * @description Tên vai trò
             * @example System Admin
             */
            name?: string;
            /**
             * @description Cấu hình quyền dạng JSON
             * @example {
             *       "users": [
             *         "CREATE",
             *         "READ",
             *         "UPDATE",
             *         "DELETE"
             *       ],
             *       "workflows": [
             *         "READ"
             *       ]
             *     }
             */
            permissions?: Record<string, never>;
        };
        CreateUserDto: {
            /**
             * @description Email đăng nhập
             * @example admin@bos.com
             */
            email: string;
            /**
             * @description Mật khẩu (tối thiểu 6 ký tự)
             * @example Admin@123
             */
            password: string;
            /**
             * @description Họ và tên
             * @example Nguyễn Văn Admin
             */
            fullName: string;
            /**
             * @description ID Phòng ban
             * @example 1
             */
            departmentId?: number;
            /**
             * @description ID Vai trò
             * @example 1
             */
            roleId?: number;
        };
        UpdateUserDto: {
            /**
             * @description Email đăng nhập
             * @example admin@bos.com
             */
            email?: string;
            /**
             * @description Họ và tên
             * @example Nguyễn Văn Admin
             */
            fullName?: string;
            /**
             * @description ID Phòng ban
             * @example 1
             */
            departmentId?: number;
            /**
             * @description ID Vai trò
             * @example 1
             */
            roleId?: number;
        };
        LoginDto: {
            /**
             * @description Email đăng nhập
             * @example admin@bos.com
             */
            email: string;
            /**
             * @description Mật khẩu
             * @example Password@123
             */
            password: string;
        };
        RegisterTenantDto: {
            /**
             * @description Tên doanh nghiệp muốn đăng ký
             * @example Công ty Cổ phần Vận tải BOS
             */
            tenantName: string;
            /**
             * @description Mã định danh duy nhất (snake_case viết thường)
             * @example vantai_bos
             */
            tenantCode: string;
            /**
             * @description Email quản trị viên đầu tiên
             * @example admin@vantaibos.com
             */
            adminEmail: string;
            /**
             * @description Mật khẩu quản trị (tối thiểu 6 ký tự)
             * @example Admin@123
             */
            adminPassword: string;
            /**
             * @description Họ và tên Quản trị viên
             * @example Nguyễn Văn Admin
             */
            adminFullName: string;
        };
        CreateEntityDto: {
            /**
             * @description Tên hiển thị của Entity
             * @example Phiếu đề xuất mua sắm
             */
            name: string;
            /**
             * @description Mã code duy nhất, viết hoa không dấu
             * @example PURCHASE_REQUEST
             */
            code: string;
            /** @description Mô tả chi tiết */
            description?: string;
            /**
             * @description Mẫu tự sinh mã nghiệp vụ (Hỗ trợ cấu hình dạng SEQ)
             * @example QTMS-{SEQ:4}
             */
            autoCodePattern?: string;
        };
        UpdateEntityDto: {
            /**
             * @description Tên hiển thị của Entity
             * @example Phiếu đề xuất mua sắm
             */
            name?: string;
            /**
             * @description Mã code duy nhất, viết hoa không dấu
             * @example PURCHASE_REQUEST
             */
            code?: string;
            /** @description Mô tả chi tiết */
            description?: string;
            /**
             * @description Mẫu tự sinh mã nghiệp vụ (Hỗ trợ cấu hình dạng SEQ)
             * @example QTMS-{SEQ:4}
             */
            autoCodePattern?: string;
        };
        CreateFieldDto: {
            /**
             * @description ID của Entity (Biểu mẫu) chứa trường này
             * @example 1
             */
            entityId: number;
            /**
             * @description Tên hiển thị
             * @example Tổng tiền
             */
            name: string;
            /**
             * @description Mã trường (snake_case chữ thường)
             * @example total_amount
             */
            code: string;
            /**
             * @description Loại trường dữ liệu (TEXT, NUMBER, DATE, SELECT, FORMULA...)
             * @example NUMBER
             */
            type: string;
            /**
             * @description Bắt buộc nhập hay không
             * @default false
             */
            isRequired: boolean;
            /**
             * @description Cấu hình JSON siêu chi tiết theo loại trường. Hỗ trợ requiredIf, showIf, min, max, regexPattern...
             * @example {
             *       "placeholder": "Nhập số tiền...",
             *       "min": 1000,
             *       "requiredIf": {
             *         "field": "category",
             *         "operator": "==",
             *         "value": "IT"
             *       }
             *     }
             */
            options?: Record<string, never>;
            /**
             * @description Thứ tự hiển thị trên giao diện
             * @default 0
             */
            orderIndex: number;
        };
        UpdateFieldDto: {
            /**
             * @description Tên hiển thị
             * @example Tổng tiền
             */
            name?: string;
            /**
             * @description Loại trường dữ liệu (TEXT, NUMBER, DATE, SELECT, FORMULA...)
             * @example NUMBER
             */
            type?: string;
            /**
             * @description Bắt buộc nhập hay không
             * @default false
             */
            isRequired: boolean;
            /**
             * @description Cấu hình JSON siêu chi tiết theo loại trường. Hỗ trợ requiredIf, showIf, min, max, regexPattern...
             * @example {
             *       "placeholder": "Nhập số tiền...",
             *       "min": 1000,
             *       "requiredIf": {
             *         "field": "category",
             *         "operator": "==",
             *         "value": "IT"
             *       }
             *     }
             */
            options?: Record<string, never>;
            /**
             * @description Thứ tự hiển thị trên giao diện
             * @default 0
             */
            orderIndex: number;
        };
        CreateRecordDto: {
            /**
             * @description ID của Entity (Biểu mẫu)
             * @example 1
             */
            entityId: number;
            /**
             * @description Dữ liệu thực tế người dùng nhập (JSON)
             * @example {
             *       "reason": "Mua máy chiếu",
             *       "total_amount": 15000000,
             *       "category": "Thiết bị IT"
             *     }
             */
            data: Record<string, never>;
        };
        UpdateRecordDto: {
            /**
             * @description Dữ liệu cập nhật dạng JSON
             * @example {
             *       "reason": "Mua Macbook Pro M3 Max cấu hình cao",
             *       "total_amount": 50000000
             *     }
             */
            data?: Record<string, never>;
        };
        CreateWorkflowDto: {
            /**
             * @description ID của Entity (Biểu mẫu) gắn với quy trình này
             * @example 1
             */
            entityId: number;
            /**
             * @description Tên quy trình
             * @example Quy trình xét duyệt mua sắm
             */
            name: string;
            /** @description Mô tả chung */
            description?: string;
            /**
             * @description Cấu hình phân quyền tầm nhìn
             * @example {
             *       "allowAll": false,
             *       "allowedDepartments": [
             *         1
             *       ]
             *     }
             */
            visibility?: Record<string, never>;
        };
        UpdateWorkflowDto: {
            /**
             * @description Tên quy trình
             * @example Quy trình xét duyệt mua sắm
             */
            name?: string;
            /** @description Mô tả chung */
            description?: string;
            /**
             * @description Cấu hình phân quyền tầm nhìn
             * @example {
             *       "allowAll": false,
             *       "allowedDepartments": [
             *         1
             *       ]
             *     }
             */
            visibility?: Record<string, never>;
        };
        CreateInstanceDto: {
            /**
             * @description ID của Bản ghi dữ liệu (Form đã submit)
             * @example 1
             */
            recordId: number;
            /**
             * @description ID của Workflow Version muốn áp dụng
             * @example 2
             */
            versionId: number;
        };
        WorkflowActionDto: {
            /**
             * @description ID của đường nối (Nút bấm) mà người dùng chọn kích hoạt
             * @example 1
             */
            transitionId: number;
            /**
             * @description Ý kiến phê duyệt
             * @example Đồng ý chuyển tiếp hồ sơ.
             */
            comment?: string;
            /**
             * @description Mã chữ ký điện tử hoặc chuỗi nét vẽ Base64 (Nếu nút yêu cầu ký duyệt)
             * @example SIGNED_BY_ADMIN_MD5_789abc
             */
            signatureData?: string;
        };
        CreateStepDto: {
            /**
             * @description ID của Workflow Version
             * @example 2
             */
            versionId: number;
            /**
             * @description Tên bước
             * @example Trưởng phòng phê duyệt
             */
            name: string;
            /**
             * @description Loại bước (USER_TASK, SYSTEM_TASK)
             * @default USER_TASK
             */
            stepType: string;
            /**
             * @description Quyền xem/sửa dữ liệu tại bước này (Step-level RBAC)
             * @example {
             *       "total_amount": "READ",
             *       "reason": "WRITE",
             *       "note": "HIDDEN"
             *     }
             */
            permissions?: Record<string, never>;
            /**
             * @description Thứ tự hiển thị trên sơ đồ
             * @default 0
             */
            orderIndex: number;
        };
        UpdateStepDto: {
            /**
             * @description Tên bước
             * @example Trưởng phòng phê duyệt
             */
            name?: string;
            /**
             * @description Loại bước (USER_TASK, SYSTEM_TASK)
             * @default USER_TASK
             */
            stepType: string;
            /**
             * @description Quyền xem/sửa dữ liệu tại bước này (Step-level RBAC)
             * @example {
             *       "total_amount": "READ",
             *       "reason": "WRITE",
             *       "note": "HIDDEN"
             *     }
             */
            permissions?: Record<string, never>;
            /**
             * @description Thứ tự hiển thị trên sơ đồ
             * @default 0
             */
            orderIndex: number;
        };
        CreateTransitionDto: {
            /**
             * @description Từ Bước (ID)
             * @example 1
             */
            fromStepId: number;
            /**
             * @description Tới Bước (ID)
             * @example 2
             */
            toStepId: number;
            /**
             * @description Logic rẽ nhánh (VD: total_amount > 20000000)
             * @example {
             *       "field": "total_amount",
             *       "operator": ">",
             *       "value": 20000000
             *     }
             */
            conditionLogic?: Record<string, never>;
            /**
             * @description Có tự động bỏ qua nếu thỏa mãn logic không?
             * @default false
             */
            autoSkip: boolean;
        };
        UpdateTransitionDto: {
            /**
             * @description Logic rẽ nhánh (VD: total_amount > 20000000)
             * @example {
             *       "field": "total_amount",
             *       "operator": ">",
             *       "value": 20000000
             *     }
             */
            conditionLogic?: Record<string, never>;
            /**
             * @description Có tự động bỏ qua nếu thỏa mãn logic không?
             * @default false
             */
            autoSkip: boolean;
        };
        CreateTemplateDto: {
            /**
             * @description ID của Entity (Biểu mẫu)
             * @example 1
             */
            entityId: number;
            /**
             * @description Tên mẫu in
             * @example Mẫu quyết định mua sắm trang thiết bị
             */
            name: string;
            /**
             * @description Cấu hình mẫu in chứa HTML (Lưu trong Json)
             * @example {
             *       "html": "<h1>PHIẾU ĐỀ XUẤT MUA SẮM</h1><p>Lý do: {{data.reason}}</p>"
             *     }
             */
            template: Record<string, never>;
        };
        UpdateTemplateDto: {
            /**
             * @description Tên mẫu in
             * @example Mẫu quyết định mua sắm trang thiết bị
             */
            name?: string;
            /**
             * @description Cấu hình mẫu in chứa HTML (Lưu trong Json)
             * @example {
             *       "html": "<h1>PHIẾU ĐỀ XUẤT MUA SẮM</h1><p>Lý do: {{data.reason}}</p>"
             *     }
             */
            template?: Record<string, never>;
        };
        CreateTenantDto: {
            /**
             * @description Tên doanh nghiệp
             * @example Công ty Cổ phần Vận tải BOS
             */
            name: string;
            /**
             * @description Mã doanh nghiệp (snake_case viết thường)
             * @example vantai_bos
             */
            code: string;
        };
        UpdateTenantDto: {
            /**
             * @description Tên doanh nghiệp
             * @example Công ty Cổ phần Vận tải BOS
             */
            name?: string;
        };
        CompleteTaskDto: {
            /** @description Ý kiến khi hoàn thành/xử lý nhiệm vụ */
            comment?: string;
        };
        DelegateTaskDto: {
            /** @description ID người được ủy quyền */
            assigneeId?: number;
            /** @description Lý do ủy quyền */
            reason?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PrometheusController_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DepartmentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDepartmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DepartmentsController_getTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DepartmentsController_getDescendants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DepartmentsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DepartmentsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DepartmentsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDepartmentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                sortBy?: string;
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                sortBy?: string;
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Trả về JWT Token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sai tài khoản hoặc mật khẩu */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registerTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterTenantDto"];
            };
        };
        responses: {
            /** @description Khởi tạo Doanh nghiệp và tài khoản Admin thành công! */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trùng Email hoặc trùng Mã doanh nghiệp */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EntitiesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                sortBy?: string;
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EntitiesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntityDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EntitiesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EntitiesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EntitiesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEntityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FieldsController_findAllByEntity: {
        parameters: {
            query: {
                entityId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FieldsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFieldDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FieldsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FieldsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FieldsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFieldDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordsController_findAllByEntity: {
        parameters: {
            query: {
                entityId: number;
                page?: number;
                limit?: number;
                sortBy?: string;
                sortOrder?: "asc" | "desc";
                searchQuery?: string;
                /** @description JSON string: {"plug_status":"DA_RUT"} */
                filters?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecordDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordsController_getLookupData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fieldId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordsController_getRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                sortBy?: string;
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkflowDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_cloneVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_updateVersionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_startInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstanceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_handleAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowActionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_getInstanceLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowStepsController_createStep: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStepDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowStepsController_removeStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowStepsController_updateStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStepDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowStepsController_createTransition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransitionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowStepsController_removeTransition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowStepsController_updateTransition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransitionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowStepsController_getPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PrintTemplatesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PrintTemplatesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PrintTemplatesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PrintTemplatesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTemplateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PrintTemplatesController_renderTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                recordId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getEntitiesSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getWorkflowsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getSpendingByDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttachmentsController_uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                    /** @description ID của Bản ghi (Không bắt buộc) */
                    recordId?: number;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttachmentsController_getPresignedUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttachmentsController_removeFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_findAllForUser: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_streamNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_markAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_markAllAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditLogsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                sortBy?: string;
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MailerController_testEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_findMyTasks: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_getAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_completeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteTaskDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_delegateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelegateTaskDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_findAll: {
        parameters: {
            query: {
                page: number;
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
